### ISSUE TITLE
What is the specific construction method for this code

### ISSUE THREAD

**Issue by ghost** [Veinhelm/Blitz3D-1.106#1]
What is the specific construction method for this code

**Comment by Veinhelm** [comment]
I don't understand. What do you mean by this?

**Comment by ghost** [comment]
> 

It's okay. The problem has been resolved

**Comment by ghost** [comment]
Hey, bro, do me a favor. Go search for a software called RadminLAN and download it. Then create a network and tell me the name and password. I need to connect to your network

**Comment by Veinhelm** [comment]
Yeah, no.
